[tools]
# "cargo:hexview" = "latest"
# "npm:@webos-tools/cli" = "latest"
# "pipx:aws-encryption-sdk-cli" = "latest"
# "pipx:toolong" = "latest"

[settings]
experimental = true
disable_tools = [
  "go", # since go can now switch toolchain versions itself, we don't want mise to do so, which can cause issues with the pkg cache
]

[settings.python]
compile = false

[settings.ruby]
compile = false
