[general]
import = [
  "~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
]

[font]
normal.family = "BerkeleyMono Nerd Font"
normal.style = "Regular"
size = 14

[window]
decorations_theme_variant = "Dark"
decorations = "Full"
padding.x = 5
padding.y = 5
opacity = 1
blur = true
option_as_alt = "OnlyLeft"

[cursor]
style.shape = "Beam"
style.blinking = "On"

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  { key = "Key0", mods = "Alt", chars = 'º' },
  { key = "Key1", mods = "Alt", chars = '¡' },
  { key = "Key2", mods = "Alt", chars = '€' },
  { key = "Key3", mods = "Alt", chars = '#' },
  { key = "Key4", mods = "Alt", chars = '¢' },
  { key = "Key5", mods = "Alt", chars = '∞' },
  { key = "Key6", mods = "Alt", chars = '§' },
  { key = "Key7", mods = "Alt", chars = '¶' },
  { key = "Key8", mods = "Alt", chars = '•' },
  { key = "Key9", mods = "Alt", chars = 'ª' },
]
