# vi: ft=ruby

tap 'burntsushi/ripgrep', 'https://github.com/BurntSushi/ripgrep.git'

brew 'coreutils'
brew 'gcc'
brew 'git-lfs'
brew 'jq'
brew 'kubernetes-cli'
brew 'libtool'
brew 'libxml2'
brew 'openssl@1.1'
brew 'pkg-config'
brew 'reattach-to-user-namespace'
brew 'ripgrep-bin'
brew 'rustup'
brew 'shellcheck'
brew 'stow'
brew 'tig'
brew 'tmux'
brew 'vim'
brew 'yq'
brew 'zsh'
