# vi: ft=ruby

tap 'burntsushi/ripgrep', 'https://github.com/BurntSushi/ripgrep.git'

brew 'coreutils'
brew 'ctags'
brew 'dnscrypt-proxy', restart_service: :changed
brew 'gcc'
brew 'git-lfs'
brew 'gpg'
brew 'jq'
brew 'kubernetes-cli'
brew 'openssl@1.1'
brew 'python'
brew 'python@2'
brew 'reattach-to-user-namespace'
brew 'ripgrep-bin'
brew 'ruby'
brew 'shellcheck'
brew 'sops'
brew 'stow'
brew 'tig'
brew 'tmux'
brew 'vim'
brew 'yq'
