#!/usr/bin/env zsh

path_has() {
  if echo "$PATH" | tr ':' '\n' | grep -x -q "$1" ; then
    return 0
  else
    return 1
  fi
}

path_append() {
  if ! path_has "$1" ; then
    PATH="$PATH:$1"
  fi
}

path_prepend() {
  if path_has "$1" ; then
    PATH="${PATH//":$1"/}"
    PATH="${PATH//"$1:"/}"
  fi
  PATH="$1:$PATH"
}

path_tidy() {
  PATH="$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')"
}

java-opt() {
  export JAVA_TOOL_OPTIONS="$1 $JAVA_TOOL_OPTIONS"
}

maven-opt() {
  export MAVEN_OPTS="$1 $MAVEN_OPTS"
}

just-configurate() {
  cosmos-ssh-to-any just-configurator $1 just-configurate
}

link-ssh() {
  pushd $HOME/.ssh
  if [ "$(readlink config)" != "$1" ]; then
    rm config; ln -s "$1" config
  fi
  popd
}

jars-in-war() {
  unzip -l *-war/target/*-SNAPSHOT.war | grep jar | awk -F '/' '{print $3}' | sort -u
}

stack-diff() {
  local STACK_TYPE=$1
  local ENVIRONMENT=$2
  dbus-launch --exit-with-session vimdiff -g tmp/templates/template-${STACK_TYPE}.${ENVIRONMENT}.*
  dbus-launch --exit-with-session vim -g tmp/templates/description-${STACK_TYPE}.${ENVIRONMENT}.next.json
}

go-here() {
  export GOPATH="${pwd}"
  export PATH="$GOPATH/bin:$PATH"
}
