#!/bin/bash

stow abcde
stow ack
stow bspwm
stow compton
stow git
stow nvim
stow pentadactyl
stow profile
stow rubocop
stow scripts
stow sxhkd
stow tmux
stow vim
stow vimperator
stow xorg
stow zsh

curl -sSL https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh > ~/.antigen.zsh

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm > /dev/null 2>&1
