#!/bin/sh

require() {
    if ! command -v "$1" > /dev/null 2>&1; then
      echo "Command $1 not found: Cannot install dotfiles automatically."
      exit 1
    fi
}

require git
require stow

case "$(uname)" in
  "Darwin")
    if ! command -v brew; then
      git clone 'https://github.com/Homebrew/brew' ../.brew
      export PATH="../.brew/bin:$PATH"
    fi
    brew tap 'homebrew/bundle' && brew bundle install
    brew link --force curl libressl
    ;;
  *) ;;
esac

git clone 'https://github.com/tmux-plugins/tpm' ../.tmux/plugins/tpm
git clone 'https://github.com/syl20bnr/spacemacs' ../.emacs.d

stow --stow --verbose \
  abcde        \
  ctags        \
  editorconfig \
  git          \
  mpd          \
  neovim       \
  rubocop      \
  scripts      \
  ssh          \
  tmux         \
  zsh          \
