confirmOnQuit: false
disableStartupPopups: true

keybinding:
  universal:
    quit: <disabled> # disable the default quit behavior
    return: q # make `q` act like `esc` (aka 'return')

git:
  paging:
    externalDiffCommand: difft --color=always

gui:
  showCommandLog: true
  authorColors:
    "*": "#f3be7c"
  theme:
    activeBorderColor:
      - "#aeaed1"
      - "bold"
    inactiveBorderColor:
      - "#606079"
    optionsTextColor:
      - "#606079"
    selectedLineBgColor:
      - "#252530"
    cherryPickedCommitFgColor:
      - "#d8647e"
    cherryPickedCommitBgColor:
      - "bg"
    markedBaseCommitFgColor:
      - "#f3be7c"
    markedBaseCommitBgColor:
      - "bg"
    unstagedChangesColor:
      - "#d8647e"
    defaultFgColor:
      - "#cdcdcd"
