AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*

Documentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
