server_names = ['cloudflare', 'cloudflare-ipv6']
listen_addresses = ['127.0.0.1:53', '[::1]:53']

cert_refresh_delay = 240
dnscrypt_servers = true
doh_servers = true
fallback_resolver = '1.1.1.1:53'
force_tcp = false
ignore_system_dns = true
max_clients = 250
timeout = 2500

ipv4_servers = true
ipv6_servers = true

log_file = 'dnscrypt-proxy.log'
log_level = 2


require_dnssec = false
require_nofilter = true
require_nolog = true


log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

block_ipv6 = false

cache = true
cache_size = 256
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60

[query_log]
  format = 'tsv'

[nx_log]
  file = 'nx.log'
  format = 'tsv'

[blacklist]

[ip_blacklist]

[schedules]

[sources]

[static]

  [static.cloudflare]
  stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk'

  [static.cloudflare-ipv6]
  stamp = 'sdns://AgcAAAAAAAAAGVsyNjA2OjQ3MDA6NDcwMDo6MTExMV06NTMg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk'
