"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
${custom.jj}\
$aws\
$kubernetes\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []

[aws]
format = 'on [☁️ ($profile )(\($region\) )]($style)'
# style = 'bold blue'

[kubernetes]
disabled = false
format = 'on [⛵ $context](dimmed green) '

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "
