#!/usr/bin/env bash

bspc config focus_follows_pointer true
bspc config auto_cancel           true

bspc config focused_border_color '#C68E17'
bspc config border_width  2
bspc config window_gap   12
bspc config top_padding  14

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a google-chrome desktop=^2
bspc rule -a vlc floating=on
bspc rule -a Screenkey manage=off
