#!/usr/bin/zsh

bspc config focus_follows_pointer true
bspc config auto_cancel           true

bspc config focused_border_color '#6d6d6d'
bspc config border_width  2
bspc config window_gap    4
bspc config top_padding   0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 一 二 三 四 五 六 七 八 七 十
