#!/bin/sh

bspc config focus_follows_pointer true
bspc config auto_cancel           true

bspc config focused_border_color '#C68E17'
bspc config border_width  2
bspc config window_gap   12
bspc config top_padding  14

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
