set nocompatible
filetype plugin indent on
syntax enable

set background=dark
colorscheme horizon

set rtp+=~/.fzf

let g:mapleader = ' '
let g:maplocalleader = '\'

" Searching
set hlsearch
set showmatch
set smartcase
set wildmode=longest,list
set wildignore+=*/.idea/*
set wildignore+=*/.git/*
set wildignore+=*/.svn/*
set wildignore+=*/vendor/*
set wildignore+=*/node_modules/*
nnoremap <silent> <Leader><space> :nohlsearch<cr>

set backspace=indent,eol,start
set balloondelay=250
set clipboard^=unnamed,unnamedplus
set completeopt=longest,menuone
set diffopt+=iwhite
set expandtab
set foldlevelstart=20
set foldmethod=syntax
set hidden
set linebreak
set nolist
set listchars=tab:——,trail:_
set modelines=1
set mouse=a
set nobackup
set noswapfile
set nowritebackup
set number
set path+=**
set scrolloff=5
set shiftwidth=2
set sidescrolloff=5
set splitbelow
set splitright
set synmaxcol=500
set tabstop=2
set textwidth=0
set timeoutlen=300
set ttymouse=sgr
set updatetime=500
set wrap
set wrapmargin=0

" Navigation
nnoremap <Leader>e :Explore<cr>
nnoremap <Leader>r :Rg<space>
nnoremap <C-t> :FZF<cr>

" Annoying typo fixes
nnoremap q: <nop>
nnoremap ; :

" Don't jump cursor when using * to search for word under cursor
nnoremap * *``

" Play q macro
nnoremap Q @q

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Highlight VCS conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

" Convenient editing of ascii-armoured encrypted files
augroup GPG
  autocmd!
  autocmd BufReadPost  *.asc :%!gpg -q -d
  autocmd BufReadPost  *.asc |redraw!
  autocmd BufWritePre  *.asc :%!gpg -q -e -a
  autocmd BufWritePost *.asc u
  autocmd VimLeave     *.asc :!clear
augroup END
