#!/usr/bin/env zsh

echo 'Current: '$(uname -r) \
  && dpkg -l 'linux-*' \
  | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' \
  | xargs sudo apt-get -y purge
