#!/usr/bin/env zsh

brew list | while read cask; do \
  if [ -t 1 ]; then
    echo -n $fg[blue] $cask $fg[white]
  else
    echo -n $cask
  fi
  brew deps $cask \
    | awk '{printf(" %s ", $0)}'
  echo ""
done
