#!/bin/bash

go get -u -v github.com/FiloSottile/gvt
go get -u -v github.com/alecthomas/gometalinter
go get -u -v github.com/constabulary/gb/...
go get -u -v github.com/divan/depscheck
go get -u -v github.com/godoctor/godoctor
go get -u -v github.com/golang/lint/golint
go get -u -v github.com/lukehoban/go-find-references
go get -u -v github.com/lukehoban/go-outline
go get -u -v github.com/maruel/panicparse/...
go get -u -v github.com/newhook/go-symbols
go get -u -v github.com/nsf/gocode
go get -u -v github.com/otium/ytdl/...
go get -u -v github.com/rogpeppe/godef
go get -u -v github.com/sqs/goreturns
go get -u -v github.com/tpng/gopkgs

go get -u golang.org/x/tools/cmd/...
go get -u honnef.co/go/unused/cmd/unused

gometalinter --install --update --force
