#!/bin/bash

GO='go get -u'

set -x

$GO github.com/HewlettPackard/gas
$GO github.com/Masterminds/glide-report
$GO github.com/alecthomas/gometalinter
$GO github.com/divan/depscheck
$GO github.com/maruel/panicparse
$GO github.com/sqs/goreturns
$GO github.com/vektra/mockery
$GO golang.org/x/tools

gometalinter --install

nvim a.go -c ':GoInstallBinaries' -c 'GoUpdateBinaries' +qall
