#!/usr/bin/env bash
set -eu

ARGS=$*

if [ -f 'Session.vim' ]; then
  ARGS+=(-S Session.vim)
fi

if command -v reattach-to-user-namespace > /dev/null 2>&1; then
  exec reattach-to-user-namespace nvim ${ARGS[@]}
fi

exec nvim ${ARGS[@]}
