#!/usr/bin/env zsh

# FINDER
echo defaults write com.apple.finder QuitMenuItem -bool YES
echo defaults write com.apple.finder AppleShowAllFiles YES
echo defaults write NSGlobalDomain AppleShowAllExtensions -bool true
echo defaults write com.apple.finder FXEnableExtensionChangeWarning -bool true
echo defaults write com.apple.finder ShowPathbar -bool true
echo defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
echo defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
echo defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# INPUT
echo defaults write NSGlobalDomain KeyRepeat -int 0
echo defaults write NSGlobalDomain InitialKeyRepeat -int 12
echo defaults write -g ApplePressAndHoldEnabled -bool false
echo defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
echo defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
echo defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# MISC
echo defaults write com.apple.dock autohide -bool true
echo defaults write com.apple.dock single-app -bool true
echo defaults write NSGlobalDomain AppleFontSmoothing -int 2
echo defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

echo chflags nohidden $HOME/Library
