#!/bin/sh
set -euo pipefail

readonly SCRIPT=$(basename "$0")
readonly USAGE=$(cat <<-EOF
  $SCRIPT: Sync all files from an S3 bucket, but only with a given prefix (kinda slow)

	USAGE:
		./$SCRIPT -b bucket -p prefix

	EOF
)

while getopts "b:p:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    p)
      PREFIX=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done


aws s3 ls --recursive "s3://$BUCKET/$PREFIX" \
  | awk '{print $4}' \
  | while IFS= read -r line; do \
      aws s3 cp "s3://$BUCKET/$line" .; \
  done
