#!/bin/sh

softwareupdate -a -i

(
  cd ~/.dotfiles && \
    git fetch --all --prune && \
    git pull --ff-only origin master
)

(
  cd ~/.dotfiles && \
    brew update && \
    brew bundle
)

go get -v -u \
  github.com/golangci/golangci-lint \
  github.com/jstemmer/gotags \
  github.com/maruel/panicparse/cmd/pp \
  github.com/y0ssar1an/q

gem update --system
gem install neovim pry

PY_DEPS='pip setuptools wheel virtualenv pipenv neovim awscli cdiff sslyze'
pip2 install -U $PY_DEPS
pip3 install -U $PY_DEPS

# npm install -g neovim

rustup self update
rustup update
