#!/bin/sh

softwareupdate -a -i
echo

echo 'Updating homebrew'
(
  cd ~/.dotfiles && \
    brew update && \
    brew bundle
)
echo

echo 'Updating ruby'
rbenv each gem update --system
rbenv each gem install --force \
  bundler \
  rubocop \
  neovim \
  pry
echo

echo 'Updating python'
pip2 install -U pip setuptools wheel virtualenv neovim awscli cdiff
pip3 install -U pip setuptools wheel virtualenv neovim awscli cdiff
echo

echo 'Updating Go tools'
go get -v -u github.com/alecthomas/gometalinter
go get -v -u github.com/maruel/panicparse/cmd/pp
go get -v -u github.com/smartystreets/goconvey
go get -v -u github.com/y0ssar1an/q
go get -v -u golang.org/x/build/version/...
go get -v -u golang.org/x/vgo
gometalinter --install
echo

echo 'Updating rust'
rustup self update
rustup update
echo
