#!/usr/bin/env zsh
set -eux

mode="$1"; shift

if [[ "$mode" =~ ^show$ ]]; then
  sudo defaults write /Applications/Utilities/XQuartz.app/Contents/Info.plist LSUIPresentationMode -int 4
elif [[ "$mode" =~ ^hide$ ]]; then
  sudo defaults delete /Applications/Utilities/XQuartz.app/Contents/Info.plist LSUIPresentationMode
else
  echo "show or hide?"
  exit 1
fi

sudo chmod 644 /Applications/Utilities/XQuartz.app/Contents/Info.plist
